# Setup

Load all packages and data needed for the analysis.

```{r setup}
# Load necessary libraries
library(tidyverse)
library(ggpubr)

data_master <-
  readr::read_delim(
    here::here(
      "DATA/MASTER.csv"
    )
  ) %>%
  tibble::as_tibble()
```

# Data wrangling

```{r}
data_work <-
  data_master %>%
  dplyr::filter(locality != "Ohu2")

vec_cat_with_par <-
  data_work %>%
  dplyr::group_by(CAT_sp) %>%
  dplyr::summarize(
    .groups = "drop",
    has_parasitoid = ifelse(
      any(!is.na(PAR_sp) & PAR_sp != ""),
      TRUE,
      FALSE
    )
  ) %>%
  filter(has_parasitoid == TRUE) %>%
  dplyr::pull("CAT_sp")

data_only_cat_with_par <-
  data_work %>%
  filter(CAT_sp %in% vec_cat_with_par)
```

# Analysis

```{r}
# helper function
get_summary_localities <- function(data_source) {
  data_source %>%
    dplyr::summarize(
      .groups = "drop",
      localities_total = dplyr::n_distinct(locality),
      # Localities where the caterpillar is parasitized (PAR_sp is not NA)
      localities_cat_and_par = dplyr::n_distinct(locality[!is.na(PAR_sp)]),
      # Localities where the caterpillar is detected but not parasitized
      localities_cat_no_par = localities_total - localities_cat_and_par,
      localities_prop_no_par = localities_cat_no_par / localities_total
    ) %>%
    return()
}
```

## Enemy free space - full dataset

```{r}
data_interaction_summary_per_interaction_pair <-
  data_work %>%
  dplyr::group_by(CAT_sp, PAR_sp) %>%
  get_summary_localities()

data_interaction_summary_per_cat <-
  data_work %>%
  dplyr::group_by(CAT_sp) %>%
  get_summary_localities()

tab_efs_work <-
  data_interaction_summary_per_interaction_pair %>%
  dplyr::filter(localities_cat_and_par > 0) %>%
  dplyr::select(CAT_sp, PAR_sp, localities_total)

readr::write_csv(
  tab_efs_work,
  here::here("output", "tab_esf_orig.csv")
)
```

## Enemy free space - only caterpillar species with parasitoids

```{r}
data_only_cat_with_par_interaction_summary_per_interaction_pair <-
  data_only_cat_with_par %>%
  dplyr::group_by(CAT_sp, PAR_sp) %>%
  get_summary_localities()

data_only_cat_with_par_interaction_summary_per_cat <-
  data_only_cat_with_par %>%
  dplyr::group_by(CAT_sp) %>%
  get_summary_localities()

data_efs_mean_long <-
  data_only_cat_with_par_interaction_summary_per_cat %>%
  dplyr::select(CAT_sp, localities_total, localities_cat_no_par, localities_prop_no_par) %>%
  dplyr::left_join(
    data_only_cat_with_par_interaction_summary_per_interaction_pair %>%
      dplyr::select(CAT_sp, PAR_sp, localities_total),
    by = "CAT_sp",
    suffix = c("_cat", "_par")
  ) %>%
  dplyr::mutate(
    efs_par = (localities_total_cat - localities_total_par) / localities_total_cat
  ) %>%
  dplyr::filter(!is.na(PAR_sp)) %>%
  dplyr::group_by(CAT_sp) %>%
  dplyr::summarise(
    efs_car_mean = mean(localities_prop_no_par, na.rm = TRUE),
    efs_par_mean = mean(efs_par, na.rm = TRUE)
  ) %>%
  tidyr::pivot_longer(
    cols = c(efs_car_mean, efs_par_mean),
    names_to = "group",
    values_to = "mean_prop_localities"
  )
```

## Calcutate summary statistic

```{r}
data_only_cat_with_par_interaction_summary_per_cat %>%
  dplyr::summarise(
    mean = mean(localities_prop_no_par, na.rm = TRUE),
    median = median(localities_prop_no_par, na.rm = TRUE)
  )

data_efs_mean_long %>%
  dplyr::filter(group == "efs_par_mean") %>%
  dplyr::summarise(
    mean = mean(mean_prop_localities, na.rm = TRUE),
    median = median(mean_prop_localities, na.rm = TRUE)
  )
```

# Visualization

```{r}
set.seed(1234)
fig_a <-
  data_efs_mean_long %>%
  dplyr::filter(group == "efs_car_mean") %>%
  ggplot2::ggplot(
    mapping = ggplot2::aes(
      x = group,
      y = mean_prop_localities,
      fill = group
    )
  ) +
  ggplot2::geom_violin() +
  ggplot2::geom_boxplot(width = 0.2, fill = "white") +
  ggplot2::geom_jitter(width = 0.2) +
  ggplot2::scale_fill_manual(values = c("#E69F00")) +
  ggplot2::scale_x_discrete(labels = c("")) + # Colorblind-friendly colors
  ggplot2::labs(
    x = "",
    y = "Proportion of localities without parasitoids",
    title = ""
  ) +
  ggplot2::coord_cartesian(ylim = c(0, 1)) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    legend.position = "none",
    axis.text.x = ggplot2::element_text(color = "black"),
    axis.title.y = ggplot2::element_text(size = 14)
  )

set.seed(1234)
fig_b <-
  data_efs_mean_long %>%
  dplyr::filter(group == "efs_par_mean") %>%
  ggplot2::ggplot(
    mapping = ggplot2::aes(
      x = group,
      y = mean_prop_localities,
      fill = group
    )
  ) +
  ggplot2::geom_violin() +
  ggplot2::geom_boxplot(width = 0.2, fill = "white") +
  ggplot2::geom_jitter(width = 0.2) +
  ggplot2::scale_fill_manual(values = c("#009E73")) +
  ggplot2::scale_x_discrete(labels = c("")) +
  ggplot2::labs(
    x = "",
    y = "",
    title = ""
  ) +
  ggplot2::coord_cartesian(ylim = c(0, 1)) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    legend.position = "none",
    axis.text.x = ggplot2::element_text(color = "black")
  )

fig_merged <-
  ggpubr::ggarrange(
    fig_a, fig_b,
    ncol = 2,
    labels = c(
      "A - Enemy free space from all parasitoids",
      "B - Enemy free space from concrete parasitoid species"
    ),
    hjust = -0.1 # Záporná hodnota zarovná text více vlevo
  )

ggplot2::ggsave(
  plot = fig_merged,
  filename = here::here("output/fig/EFS_means.png"),
  bg = "white",
  width = 1933,
  height = 1597,
  units = "px"
)
```



