```{r}
library(igraph)
library(ggraph)
library(tidygraph)

```

```{r}
# Example edge list
interactions <- data.frame(
  from = c("Plant1","Plant1", "Plant2", "Plant2", "Caterpillar1", "Caterpillar2"),
  to = c("Caterpillar1","Caterpillar2", "Caterpillar2","Caterpillar2", "Parasitoid1", "Parasitoid2")
)

# Create an igraph object
food_web <- graph_from_data_frame(interactions, directed = TRUE)

ggraph(food_web, layout = "fr") +  # 'fr' is the Fruchterman-Reingold layout
  geom_edge_link(arrow = arrow(length = unit(4, "mm")), end_cap = circle(3, 'mm')) +
  geom_node_point(size = 5, color = "skyblue") +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void()

```

```{r}
# Library
library(networkD3)
library(dplyr)
 
# A connection data frame is a list of flows with intensity for each flow
links <- data.frame(
  source=c("group_A","group_A", "group_B", "group_C", "group_C", "group_E"), 
  target=c("group_C","group_D", "group_E", "group_F", "group_G", "group_H"), 
  value=c(2,3, 2, 3, 1, 3)
  )
 
# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame(
  name=c(as.character(links$source), 
  as.character(links$target)) %>% unique()
)
 
# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
links$IDsource <- match(links$source, nodes$name)-1 
links$IDtarget <- match(links$target, nodes$name)-1
 
# Make the Network
p <- sankeyNetwork(Links = links, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name", 
              sinksRight=FALSE)
p


```


```{r}
# Load libraries
library(igraph)
library(ggraph)
library(tidyverse)

# Example data for a food web
nodes <- data.frame(
  id = c("Plant1", "Plant2", "Caterpillar1", "Caterpillar2", "Parasitoid1", "Parasitoid2"),
  type = c("Plant", "Plant", "Caterpillar", "Caterpillar", "Parasitoid", "Parasitoid")
)

edges <- data.frame(
  from = c("Plant1", "Plant2", "Plant1", "Plant2", "Caterpillar1", "Caterpillar2"),
  to = c("Caterpillar1", "Caterpillar2", "Caterpillar2", "Caterpillar1", "Parasitoid1", "Parasitoid2")
)

# Create a graph object
food_web <- graph_from_data_frame(d = edges, vertices = nodes, directed = TRUE)

# Define colors for each node type
node_colors <- c("Plant" = "green", "Caterpillar" = "orange", "Parasitoid" = "red")

# Plot the food web using ggraph
ggraph(food_web, layout = "stress") +
  geom_edge_link(aes(edge_alpha = 0.8), arrow = arrow(length = unit(4, "mm")), end_cap = circle(3, "mm")) +
  geom_node_point(aes(fill = nodes$type, shape = nodes$type), size = 10) +
  scale_fill_manual(values = node_colors) +
  geom_node_text(aes(label = name), vjust = 1.5, size = 4) +
  theme_void() +
  theme(legend.position = "none") +
  ggtitle("Food Web Visualization")
```

