#Diversity indices
```{r}
library(dplyr)
library(vegan)
library(ggplot2)
library(reshape)
library(betapart)
library(skimr)
library(tibble)
library(readxl)

# Full data
MASTER <- read_excel(here::here("DATA/MASTER.xlsx")) %>% as_tibble() %>% 
  dplyr:: filter(locality != "Ohu2")



# Loading distance matrix
Distance <- read.csv2(here::here("DATA", "Distance.csv"), row.names = 1) # loading distance matrix of localities
#Distance <-Distance[!(rownames(Distance) == "Ohu2"), !(colnames(Distance) == "Ohu2")]

# Prepare the distance matrix for a figure
Distance_fig <- read.csv2(here::here("DATA/Distance.csv"))

distance_2 <- reshape::melt(Distance_fig)   #melt a matrix
#distance_2 <- distance_2[!(distance_2$X == "Ohu2" | distance_2$variable == "Ohu2"), ]

distance_plot <- dplyr::rename (distance_2, Locality_A = X, Locality_B = variable, distance = value)  # rename columns

# data for parasitoids
para_pivot<-  MASTER  %>%
  select(locality, PAR_sp, Par_remove)

para_pivot <- para_pivot %>% 
  filter(Par_remove == "0")

para_pivot2 <- as.matrix(table(para_pivot$locality, para_pivot$PAR_sp))  # dataframe ready for indices
para_pivot2[is.na(para_pivot2)] <- 0 # Replacing NA values with 0
para_pivot_P_A <- para_pivot2
para_pivot_P_A [para_pivot_P_A > 0] <- 1 #converts from abundance to P/A - for Sorensen index only

# Make a dataframe for caterpillars
cat_pivot <-  MASTER %>% 
   select(locality, CAT_sp)

cat_pivot2 <- as.matrix(table(cat_pivot$locality, cat_pivot$CAT_sp))  # dataframe ready for indices
cat_pivot2[is.na(cat_pivot2)] <- 0 # Replacing NA values with 0
cat_pivot_P_A <- cat_pivot2
cat_pivot_P_A [cat_pivot_P_A > 0] <- 1 #converts from abundance to P/A for Sorensen index only
```


```{r Counts}
skim(MASTER)

family_species <- MASTER %>%
   select(PAR_sp, locality, PLANT_sp)

# Count the number of unique species in each locality
species_locality_count <- family_species %>%
   group_by(locality, PLANT_sp) %>%
   summarise(
      species_count = n_distinct(PAR_sp),  # Count unique species
      abundance = n()  # Count total occurrences (abundance)
   )

# View the result
species_locality_count

family_species_cat <- MASTER %>%
   select(CAT_sp, locality)

# Count the number of unique species in each locality
species_locality_count_cat <- family_species_cat %>%
   group_by(locality) %>%
   summarise(
      species_count = n_distinct(CAT_sp),  # Count unique species
      abundance = n()  # Count total occurrences (abundance)
   )
# View the result
species_locality_count_cat
```

# Bray-Curtis
```{r Bray-Curtis, echo=FALSE}
# Bray-Curtis index computation and analysis for a given community
calculate_bray_curtis <- function(data_matrix, distance_matrix, guild_name) {
  
  # Compute Bray-Curtis distance matrix
  bc_res <- vegan::vegdist(data_matrix, method = "bray", binary = FALSE, diag = TRUE) %>% as.matrix()
  
  # Mantel test
  bc_res_mantel <- vegan::mantel(bc_res, distance_matrix, method = "spear")
  
  # Prepare data for plotting
  bc_melted <- reshape::melt(bc_res)
  bc_figure <- dplyr::rename(bc_melted, Locality_A = X1, Locality_B = X2, hodnota = value) %>%
    dplyr::mutate(guild = guild_name)
  
  bc_fig_table <- merge(bc_figure, distance_plot, by = c("Locality_A", "Locality_B")) %>%
    dplyr::filter(hodnota > 0) %>% 
    add_column(indexy = "Bray-Curtis")
  
  # Linear model for Bray-Curtis vs Distance
  bc_lm <- lm(hodnota ~ distance, data = bc_fig_table)
  
  # Summary statistics
  bc_summary <- bc_fig_table %>%
    dplyr::summarise(mean_BC = mean(hodnota), sd_BC = sd(hodnota))
  
  # Create result table
  mantel_result <- data.frame(
    index = "Bray-Curtis",
    Community = guild_name,
    mean = round(bc_summary$mean_BC, 3),
    sd = round(bc_summary$sd_BC, 3),
    test = "Mantel",
    statistic = round(bc_res_mantel$statistic, 3),
    p.value = round(bc_res_mantel$signif, 3),
    Dataset = "Full",
    stringsAsFactors = FALSE
  )
  
  # Return all results as a list
  return(list(
    mantel_result = mantel_result,
    linear_model = summary(bc_lm),
    summary_stats = bc_summary,
    bc_fig_table = bc_fig_table
  ))
}

# Apply the function to Parasitoids
parasitoid_results <- calculate_bray_curtis(para_pivot2, Distance, "Parasitoids")
print(parasitoid_results$mantel_result)
BC_par <- (parasitoid_results$bc_fig_table)
# Apply the function to Caterpillars
caterpillar_results <- calculate_bray_curtis(cat_pivot2, Distance, "Caterpillars")
print(caterpillar_results$mantel_result)
BC_cat <- (caterpillar_results$bc_fig_table)

```


# Chao-Sorensen
```{r Chao-Sorensen, echo=FALSE}
# Chao-Sorensen index computation and analysis for a given community
calculate_chao_sorensen <- function(data_matrix, distance_matrix, guild_name) {
  
  # Compute Chao-Sorensen distance matrix
  cs_res <- CommEcol::dis.chao(data_matrix, index = "sorensen", version = "rare", freq = NULL) %>% as.matrix()
  
  # Mantel test
  cs_res_mantel <- vegan::mantel(cs_res, distance_matrix, method = "spear")
  
  # Prepare data for plotting
  cs_melted <- reshape::melt(cs_res)
  cs_figure <- dplyr::rename(cs_melted, Locality_A = X1, Locality_B = X2, hodnota = value) %>%
    dplyr::mutate(guild = guild_name)
  
  cs_fig_table <- merge(cs_figure, distance_plot, by = c("Locality_A", "Locality_B")) %>%
    dplyr::filter(hodnota > 0) %>% 
    add_column(indexy = "Chao-Sorensen")
  
  # Linear model for Chao-Sorensen vs Distance
  cs_lm <- lm(hodnota ~ distance, data = cs_fig_table)
  
  # Summary statistics
  cs_summary <- cs_fig_table %>%
    dplyr::summarise(mean_CS = mean(hodnota), sd_CS = sd(hodnota))
  
  # Create result table
  mantel_result <- data.frame(
    index = "Chao-Sorensen",
    Community = guild_name,
    mean = round(cs_summary$mean_CS, 3),
    sd = round(cs_summary$sd_CS, 3),
    test = "Mantel",
    statistic = round(cs_res_mantel$statistic, 3),
    p.value = round(cs_res_mantel$signif, 3),
    Dataset = "Full",
    stringsAsFactors = FALSE
  )
  
  # Return all results as a list
  return(list(
    mantel_result = mantel_result,
    linear_model = summary(cs_lm),
    summary_stats = cs_summary,
    cs_fig_table = cs_fig_table
  ))
}

# Apply the function to Parasitoids
parasitoid_results_cs <- calculate_chao_sorensen(para_pivot2, Distance, "Parasitoids")
print(parasitoid_results_cs$mantel_result)
CS_par <-(parasitoid_results_cs$cs_fig_table)
# Apply the function to Caterpillars
caterpillar_results_cs <- calculate_chao_sorensen(cat_pivot2, Distance, "Caterpillars")
print(caterpillar_results_cs$mantel_result)
CS_cat <-(caterpillar_results_cs$cs_fig_table)


```
# Sorensen
```{r Sorensen, echo=FALSE}
# Sorensen index computation and analysis for a given community
calculate_sorensen <- function(data_presence_absence, distance_matrix, guild_name) {
  
  # Compute Sorensen dissimilarity
  sorensen_res <- beta.pair(data_presence_absence)
  sorensen_matrix <- as.matrix(sorensen_res$beta.sor) # Extract Sorensen index
  
  # Mantel test
  sor_mantel <- vegan::mantel(sorensen_matrix, distance_matrix, method = "spear")
  
  # Prepare data for plotting
  sorensen_melted <- reshape::melt(sorensen_matrix)
  sorensen_figure <- dplyr::rename(sorensen_melted, Locality_A = X1, Locality_B = X2, hodnota = value) %>%
    dplyr::mutate(guild = guild_name)
  
  sor_fig_table <- merge(sorensen_figure, distance_plot, by = c("Locality_A", "Locality_B")) %>%
    dplyr::filter(hodnota > 0) %>% 
    add_column(indexy = "Sorensen")
  
  # Linear model for Sorensen vs Distance
  sor_lm <- lm(hodnota ~ distance, data = sor_fig_table)
  
  # Summary statistics
  sor_summary <- sor_fig_table %>%
    dplyr::summarise(mean_sor = mean(hodnota), sd_sor = sd(hodnota))
  
  # Create result table
  mantel_result <- data.frame(
    index = "Sorensen",
    Community = guild_name,
    mean = round(sor_summary$mean_sor, 3),
    sd = round(sor_summary$sd_sor, 3),
    test = "Mantel",
    statistic = round(sor_mantel$statistic, 3),
    p.value = round(sor_mantel$signif, 3),
    Dataset = "Full",
    stringsAsFactors = FALSE
  )
  
  # Return all results as a list
  return(list(
    mantel_result = mantel_result,
    linear_model = summary(sor_lm),
    summary_stats = sor_summary,
    sor_fig_table =sor_fig_table
  ))
}

# Apply the function to Parasitoids
parasitoid_results_sor <- calculate_sorensen(para_pivot_P_A, Distance, "Parasitoids")
print(parasitoid_results_sor$mantel_result)
SOR_par <-(parasitoid_results_sor$sor_fig_table)
# Apply the function to Caterpillars
caterpillar_results_sor <- calculate_sorensen(cat_pivot_P_A, Distance, "Caterpillars")
print(caterpillar_results_sor$mantel_result)
SOR_cat <-(caterpillar_results_sor$sor_fig_table)
```

Summary of Indices
```{r}
# Combine all tables into one
all_mantel_results <- rbind(mantel_result_cat_SOR, mantel_result_par_SOR,mantel_result_cat_CS, mantel_result_par_CS, mantel_result_cat_BC, mantel_result_Par_BC)

# Print the merged table# Print the merged tablemantel_result_Par_BC
print(all_mantel_results)

all_mantel_results$Dataset <- "Full"

```

# Subsampling
# SOR - sub
```{r SOR - Subsampling, echo=FALSE}
library(tidyr)
library(purrr)
MASTER <- read_excel(here::here("DATA/MASTER.xlsx")) %>% as_tibble() # loading the master file with all data available (detailed info with old sp_code etc check Master_2023 file)
Distance <- read.csv2("DATA/Distance.csv", row.names=1) # loading distance matrix of

data_testing <- MASTER %>% 
  filter(remove_cat == "0") %>% 
  select(locality,CAT_sp, PAR_sp, guild, PLANT_sp)

# calculate the total abundance of parasitoids in each plot
n_par_specimens_in_site <-
  data_testing %>% 
  filter(guild == "PAR") %>%
  drop_na() %>% 
  group_by(locality) %>% 
  summarise(
    .groups= "keep",
    N= n()) %>% 
  ungroup()

# pre-allocate tibble with all sites 
site_tibble <-  
  MASTER %>% 
  group_by(locality) %>% 
  summarise(.groups = "keep")

#----------------------------------------------------------#
# 2.2 Function for subsampling -----
#----------------------------------------------------------#

set.seed(1234)

n_rand <-  999

# pre-alocate space

res_list <- vector("list", length = n_rand)

for (i in 1:n_rand) {
  
  #print(i)
  
  cat_randomly_resampled  <- 
    as.list(site_tibble$locality) %>% 
    purrr::map_df(
      .x = .,
      .f = function(x){
        
        N_para <-
          n_par_specimens_in_site %>% 
          filter(locality == x) %>% 
          dplyr::select(N) %>% 
          pluck(1)
        
        res <-
          MASTER %>% 
          filter(locality == x) %>% 
          sample_n(., size = N_para)
        
        return(res)
      }
    ) %>% 
    bind_rows()
  
  
  #----------------------------------------------------------#
  # 2.3 Saving results and count mean for the data -----
  #----------------------------------------------------------#
  
  df <- 
    cat_randomly_resampled %>% 
    dplyr::select(locality, CAT_sp) %>%
    group_by(locality, CAT_sp) %>% 
    summarise(
      .groups = "keep",
      N = n()) %>% 
    ungroup() %>% 
    pivot_wider(names_from = CAT_sp, values_from = N) %>% 
    replace(is.na(.), 0) %>% 
    column_to_rownames(var = "locality")
  
  df_pres <- df
  
  df_pres[df_pres>1]<-1
  
  #----------------------------------------------------------#
  # 2.4 Sorensen comparison-----
  #----------------------------------------------------------#
 
  
sorensen_dis <- beta.pair(df_pres)   
Sor_res <- (as.matrix(sorensen_dis$beta.sor))
   
    
  
  
  res_list[[i]] <-Sor_res
  
}

#  calculate a mean
Y <- do.call(cbind, res_list)
Y <- array(Y, dim = c(dim(res_list[[1]]), length(res_list)))

Sor_res_mean <-
  apply(Y, c(1, 2), mean, na.rm = TRUE)

rownames(Sor_res_mean) <- c("Elem", "Morox", "Niksek", "Ohu1", "Ohu2", "Utai", "Wamangu", "Wanang","Yapsiei")
colnames(Sor_res_mean) <- c("Elem", "Morox", "Niksek", "Ohu1", "Ohu2", "Utai", "Wamangu", "Wanang","Yapsiei")

# calculate a mean of the results
Sor_mean_sub<-melt(Sor_res_mean)
Sor_mean_sub<- summarise(Sor_mean_sub,
                     mean_Sor = mean(value),
                     sd_Sor = sd(value))
Sor_mean_sub



#----------------------------------------------------------#
# 2.5 Mantel test-----
#----------------------------------------------------------#
library(vegan)
# Distance between localities


res_mantel_sor_sub <-
  mantel(Sor_res_mean, Distance , method="spear")


Sorensen_para_sub<- melt(Sor_res_mean)
Sorensen_figure_sub <- dplyr::rename (Sorensen_para_sub, Locality_A = X1, Locality_B = X2, hodnota = value)
Sorensen_figure_sub  <- Sorensen_figure_sub  %>%
  add_column(guild = "Caterpillars-subsampled")
SOR_fig_subsampled <-merge(Sorensen_figure_sub, distance_plot, by=c("Locality_A", "Locality_B")) %>% 
  filter (hodnota > 0) %>% 
    add_column(indexy = "Sorensen")


  SOR_lm_hous <- lm(hodnota~distance, data = Sorensen_fig_subsampled)
SOR_lm_hous

cat_SOR_sub_mean <- summarise(Sorensen_fig_subsampled,
                     mean_sor = mean(hodnota),
                     sd_sor = sd(hodnota)) 
cat_SOR_sub_mean

mantel_result_cat_SOR_sub <- data.frame(
  index ="Sorensen",
  Community = "Caterpillars-subsampled",
  mean = round(cat_SOR_sub_mean$mean,3),
  sd = round(cat_SOR_sub_mean$sd,3),
  test = "Mantel",
  statistic = round (res_mantel_sor_sub$statistic,3),
  p.value = round(res_mantel_sor_sub$signif,3),    Dataset = "Full",
  stringsAsFactors = FALSE
)
print(mantel_result_cat_SOR_sub)


```
# BC - sub
```{r BC - subsampling}
MASTER <- read_excel("DATA/MASTER.xlsx") %>% as_tibble() # loading the master file with all data available (detailed info with old sp_code etc check Master_2023 file)
Distance <- read.csv2("DATA/Distance.csv", row.names=1) # loading distance matrix of

data_testing <- MASTER %>% 
  filter(remove_cat == "0") %>% 
  select(locality,CAT_sp, PAR_sp, guild, PLANT_sp)



# calculate the total abundance of parasitoids in each plot
n_par_specimens_in_site <-
  data_testing %>% 
  filter(guild == "PAR") %>%
  drop_na() %>% 
  group_by(locality) %>% 
  summarise(
    .groups= "keep",
    N= n()) %>% 
  ungroup()

# pre-allocate tibble with all sites 
site_tibble <-  
  data_testing %>% 
  group_by(locality) %>% 
  summarise(.groups = "keep")




#----------------------------------------------------------#
# 2.2 Function for subsampling -----
#----------------------------------------------------------#

set.seed(1234)

n_rand <-  1000


res_list <- vector("list", length = n_rand)

for (i in 1:n_rand) {
 
  #print(i)
  
   cat_randomly_resampled  <- 
    as.list(site_tibble$locality) %>% 
    purrr::map_df(
      .x = .,
      .f = function(x){
        
        N_para <-
          n_par_specimens_in_site %>% 
          filter(locality == x) %>% 
          dplyr::select(N) %>% 
          pluck(1)
        
        res <-
          data_testing %>% 
          filter(locality == x) %>% 
          sample_n(., size = N_para)
        
        return(res)
      }
    ) %>% 
    bind_rows()
   
  df <- 
    cat_randomly_resampled %>% 
    dplyr::select(locality, CAT_sp) %>%
    group_by(locality, CAT_sp) %>% 
    summarise(
      .groups = "keep",
      N = n()) %>% 
    ungroup() %>% 
    pivot_wider(names_from = CAT_sp, values_from = N) %>% 
    replace(is.na(.), 0) %>% 
    column_to_rownames(var = "locality")
  
  
    
#----------------------------------------------------------#
# 2.4 Bray_curtis comparison-----
#----------------------------------------------------------#


BC_res <- vegdist(df, method="bray", binary=FALSE, diag=TRUE) %>% 
  as.matrix()


res_list[[i]] <- BC_res

}

#  calculate a mean
Y <- do.call(cbind, res_list)
Y <- array(Y, dim = c(dim(res_list[[1]]), length(res_list)))

BC_res_mean <-
  apply(Y, c(1, 2), mean, na.rm = TRUE)


rownames(BC_res_mean) <- c("Elem", "Morox", "Niksek", "Ohu1", "Ohu2", "Utai", "Wamangu", "Wanang","Yapsiei")
colnames(BC_res_mean) <- c("Elem", "Morox", "Niksek", "Ohu1", "Ohu2", "Utai", "Wamangu", "Wanang","Yapsiei")


# calculate a mean of the results
BC_melt<-melt(BC_res_mean)
BC_melt <- dplyr::rename (BC_melt, Locality_A = X1, Locality_B = X2, hodnota = value)

BC_melt_subsampling <- BC_melt %>% 
  add_column(guild = "Caterpillars-subsampled")
BC_fig_subsampled <-merge(BC_melt_subsampling, distance_plot, by=c("Locality_A", "Locality_B")) %>% 
  filter (hodnota > 0) %>% 
    add_column(indexy = "Bray-Curtis")



BC_mean_sub <- summarise(BC_melt,
                     mean_BC = mean(value),
                     sd_BC = sd(value))


mantel_result_cat_BC_subsampled <- data.frame(
  index ="Bray-Curtis",
  Community = "Caterpillars-subsampled",
  mean = round(BC_mean_sub$mean,3),
  sd = round(BC_mean_sub$sd,3),
  test = "Mantel",
  statistic = round (BC_cat_res_mantel$statistic,3),
  p.value = round(BC_cat_res_mantel$signif,3),
  stringsAsFactors = FALSE
)
print(mantel_result_cat_BC_subsampled)
#BC_mean


```

# CS - sub
```{r CS - subsampling, echo=FALSE}
# calculate the total abundance of parasitoids in each plot
n_par_specimens_in_site <-
  MASTER %>% 
  filter(guild == "PAR") %>%
  drop_na() %>% 
  group_by(locality) %>% 
  summarise(
    .groups= "keep",
    N= n()) %>% 
  ungroup()

# pre-allocate tibble with all sites 
site_tibble <-  
  MASTER %>% 
  group_by(locality) %>% 
  summarise(.groups = "keep")


#----------------------------------------------------------#
# 2.2 Function for subsampling -----
#----------------------------------------------------------#

set.seed(1234)

n_rand <-  1000

# pre-alocate space

res_list <- vector("list", length = n_rand)

for (i in 1:n_rand) {
  
  # Generate random resampled data for each iteration
  cat_randomly_resampled <- 
    as.list(site_tibble$locality) %>% 
    purrr::map_df(
      .x = .,
      .f = function(x) {
        
        # Get the number of PAR specimens in the site
        N_para <- 
          n_par_specimens_in_site %>% 
          filter(locality == x) %>% 
          dplyr::select(N) %>% 
          pull(1)
        
        # Check if N_para is valid
        if (is.na(N_para) || length(N_para) == 0 || N_para == 0) {
          return(tibble()) # Return an empty tibble if no valid N_para
        }
        
        # Resample data
        res <- 
          MASTER %>% 
          filter(locality == x) %>% 
          sample_n(size = N_para, replace = FALSE)
        
        return(res)
      }
    )
  
  # Continue processing only if data was generated
  if (nrow(cat_randomly_resampled) > 0) {
    
    # Create a summarized dataframe
    df <- 
      cat_randomly_resampled %>% 
      dplyr::select(locality, CAT_sp) %>% 
      group_by(locality, CAT_sp) %>% 
      summarise(
        .groups = "keep",
        N = n()
      ) %>% 
      ungroup() %>% 
      pivot_wider(names_from = CAT_sp, values_from = N) %>% 
      replace(is.na(.), 0) %>% 
      column_to_rownames(var = "locality")
    
    # Calculate Chao-Sorensen index
    Chao_Sor_res <- 
      CommEcol::dis.chao(df, index = "sorensen", version = "rare", freq = NULL) %>% 
      as.matrix()
    
    # Save results
    res_list[[i]] <- Chao_Sor_res
  } else {
    res_list[[i]] <- NA # Save NA if no data generated
  }
}


#  calculate a mean
Y <- do.call(cbind, res_list)
Y <- array(Y, dim = c(dim(res_list[[1]]), length(res_list)))

Chao_Sor_res_mean <-
apply(Y, c(1, 2), mean, na.rm = TRUE)


rownames(Chao_Sor_res_mean) <- c("Elem", "Morox", "Niksek", "Ohu1", "Ohu2", "Utai", "Wamangu", "Wanang","Yapsiei")
colnames(Chao_Sor_res_mean) <- c("Elem", "Morox", "Niksek", "Ohu1", "Ohu2", "Utai", "Wamangu", "Wanang","Yapsiei")


# calculate a mean of the results
CS_melt_sub<-melt(Chao_Sor_res_mean)
CS_mean_sub <- summarise(CS_melt_sub,
                      mean_CS = mean(value),
                      sd_CS = sd(value))
#----------------------------------------------------------#
# 2.5 Mantel test-----
#----------------------------------------------------------#
library(vegan)
# Distance between localities
Distance2 <- 
  read.csv2(
    here::here("~/ownCloud/000_/000_R_stat/Beta_diversity/data/input/Distance22.csv"), row.names=1)

res_mantel <-
mantel(Chao_Sor_res_mean, Distance2 , method="spear")

saveRDS(
  Chao_Sor_res_mean,
  here::here("~/ownCloud/000_/000_R_stat/ParaDiv_2023/output/Chao_Sor_res_mean.rds")
)

saveRDS(
  res_mantel,
  here::here("~/ownCloud/000_/000_R_stat/ParaDiv_2023/output/mantel_result.rds")
)


CS_subsampled_res_cat <- rename (CS_melt, Locality_A = X1, Locality_B = X2, hodnota = value)
CS_subsampled_figure_cat <- CS_subsampled_res_cat %>%
  add_column(guild = "Caterpillars-subsampled") %>% 
  filter (hodnota > 0) %>% 
    add_column(indexy = "Chao-Sorensen")
  
CS_fig_subsampled<- merge(CS_subsampled_figure_cat, distance_plot, by=c("Locality_A", "Locality_B"))


CS_lm_hou <- lm(hodnota~distance, data = CS_subsampled_figure_cat)
CS_lm_hou


mantel_result_cat_CS_sub <- data.frame(
  index ="Chao-Sorensen",
  Community = "Caterpillars-subsampled",
  mean = round(CS_mean_sub$mean,3),
  sd = round(CS_mean_sub$sd,3),
  test = "Mantel",
  statistic = round (res_mantel_CS_sub$statistic,3),
  p.value = round(res_mantel_CS_sub$signif,3),    Dataset = "Full",
  stringsAsFactors = FALSE
)
print(mantel_result_cat_CS_sub)

```


# Table
```{r Tabulka}
# Combine all tables into one - main WITHOUT subsampling
all_mantel_results <- rbind(mantel_result_cat_SOR, mantel_result_par_SOR,mantel_result_cat_CS, mantel_result_par_CS, mantel_result_cat_BC, mantel_result_Par_BC)
# Print the merged table# Print the merged tablemantel_result_Par_BC
print(all_mantel_results)


# Combine data for figure

figure_1_merged <- rbind(BC_par, BC_cat, BC_fig_subsampled, CS_par, CS_cat, CS_fig_subsampled,SOR_par, SOR_cat, SOR_fig_subsampled)
```

# Figure 1 - violin plot
```{r}
figure_1_merged <- figure_1_merged %>% 
  dplyr::filter(!(Locality_A == "Ohu2" | Locality_B == "Ohu2"))
ind_BC <- figure_1_merged %>% 
  dplyr::filter(indexy == "Bray-Curtis")

ind_CS <- figure_1_merged %>% 
  dplyr::filter(indexy == "Chao-Sorensen")

ind_SOR <- figure_1_merged %>% 
  dplyr::filter(indexy == "Sorensen")


# Ensure 'guild' is a factor with the desired order
ind_BC$guild <- factor(ind_BC$guild, 
                              levels = c("Parasitoids", "Caterpillars", "Caterpillars-subsampled"))

# Create the plot
BC_FIG_1 <- ggplot(ind_BC, aes(x = guild, y = hodnota, fill = guild)) +
  geom_violin(trim = FALSE) +  # Violin plot without trimming
  geom_boxplot(width = 0.1, outlier.shape = NA) +  # Boxplot with no outliers shown
  geom_jitter(position = position_jitter(0.2), aes(color = guild), show.legend = FALSE) +  # Jitter with color, no legend
  scale_fill_manual(values = c("Parasitoids" = "darkgreen", 
                               "Caterpillars" = "darkorange", 
                               "Caterpillars-subsampled" = "#ffb681")) +
  scale_color_manual(values = c("Parasitoids" = "black", 
                               "Caterpillars" = "black", 
                               "Caterpillars-subsampled" = "black"))  +
  coord_cartesian(ylim = c(0, 1)) +
  labs(title = "Bray-Curtis", x = "Guild", y = "Dissimilarity", fill = "Guild") +  # Keep only one legend for 'fill'
  theme_classic(base_size = 20) ;BC_FIG_1

# Display the plot
BC_FIG_1

# Create the plot
CS_FIG_1 <- ggplot(ind_CS, aes(x = guild, y = hodnota, fill = guild)) +
  geom_violin(trim = FALSE) +  # Violin plot without trimming
  geom_boxplot(width = 0.1, outlier.shape = NA) +  # Boxplot with no outliers shown
  geom_jitter(position = position_jitter(0.2), aes(color = guild), show.legend = FALSE) +  # Jitter with color, no legend
  scale_fill_manual(values = c("Parasitoids" = "darkgreen", 
                               "Caterpillars" = "darkorange", 
                               "Caterpillars-subsampled" = "#ffb681")) +
  scale_color_manual(values = c("Parasitoids" = "black", 
                               "Caterpillars" = "black", 
                               "Caterpillars-subsampled" = "black"))  +
  coord_cartesian(ylim = c(0, 1)) +
  labs(title = "Chao-Sorensen", x = "Guild", y = "Dissimilarity", fill = "Guild") +  # Keep only one legend for 'fill'
  theme_classic(base_size = 20) ;CS_FIG_1

# Display the plot
CS_FIG_1

# Create the plot
SOR_FIG_1 <- ggplot(ind_SOR, aes(x = guild, y = hodnota, fill = guild)) +
  geom_violin(trim = FALSE) +  # Violin plot without trimming
  geom_boxplot(width = 0.1, outlier.shape = NA) +  # Boxplot with no outliers shown
  geom_jitter(position = position_jitter(0.2), aes(color = guild), show.legend = FALSE) +  # Jitter with color, no legend
  scale_fill_manual(values = c("Parasitoids" = "darkgreen", 
                               "Caterpillars" = "darkorange", 
                               "Caterpillars-subsampled" = "#ffb681")) +
  scale_color_manual(values = c("Parasitoids" = "black", 
                               "Caterpillars" = "black", 
                               "Caterpillars-subsampled" = "black"))  +
  coord_cartesian(ylim = c(0, 1)) +
  labs(title = "Sorensen", x = "Guild", y = "Dissimilarity", fill = "Guild") +  # Keep only one legend for 'fill'
  theme_classic(base_size = 20) ;SOR_FIG_1

# Display the plot
SOR_FIG_1
```

# Figure 1 - without subsampling - theoretically for the interactive figure
```{r}
figure_1_merged <- figure_1_merged %>% 
  dplyr::filter(!(Locality_A == "Ohu2" | Locality_B == "Ohu2"))
ind_BC <- figure_1_merged %>% 
  dplyr::filter(indexy == "Bray-Curtis")

ind_CS <- figure_1_merged %>% 
  dplyr::filter(indexy == "Chao-Sorensen")

ind_SOR <- figure_1_merged %>% 
  dplyr::filter(indexy == "Sorensen")


# Ensure 'guild' is a factor with the desired order
ind_BC$guild <- factor(ind_BC$guild, 
                              levels = c("Caterpillars", "Parasitoids"))
ind_BC_simple <- ind_BC %>% 
  dplyr::filter(! (guild == "Caterpillars-subsampled"))
ind_CS_simple <- ind_CS %>% 
  dplyr::filter(! (guild == "Caterpillars-subsampled"))
ind_SOR_simple <- ind_SOR %>% 
  dplyr::filter(! (guild == "Caterpillars-subsampled"))

# Create the plot
BC_FIG_1_simple <- ggplot(ind_BC_simple, aes(x = guild, y = hodnota, fill = guild)) +
  geom_violin(width = 0.4, trim = FALSE) +  # Violin plot without trimming
  geom_boxplot(width = 0.1, outlier.shape = NA) +  # Boxplot with no outliers shown
  geom_jitter(position = position_jitter(0.2), aes(color = guild), show.legend = FALSE) +  # Jitter with color, no legend
  scale_fill_manual(values = c("Parasitoids" = "darkgreen", 
                               "Caterpillars" = "darkorange")) +
  scale_color_manual(values = c("Parasitoids" = "black", 
                               "Caterpillars" = "black"))  +
  coord_cartesian(ylim = c(0, 1)) +
  labs(y = "Dissimilarity") +  # Keep only one legend for 'fill'
  theme_classic(base_size = 20) ;BC_FIG_1_simple

# Display the plot
BC_FIG_1_simple

# Ensure 'guild' is a factor with the desired order
ind_CS$guild <- factor(ind_CS$guild, 
                              levels = c("Caterpillars", "Parasitoids"))

# Create the plot
CS_FIG_1_simple <- ggplot(ind_CS_simple, aes(x = guild, y = hodnota, fill = guild)) +
  geom_violin(trim = FALSE) +  # Violin plot without trimming
  geom_boxplot(width = 0.1, outlier.shape = NA) +  # Boxplot with no outliers shown
  geom_jitter(position = position_jitter(0.2), aes(color = guild), show.legend = FALSE) +  # Jitter with color, no legend
    scale_fill_manual(values = c("Parasitoids" = "darkgreen", 
                               "Caterpillars" = "darkorange")) +
  scale_color_manual(values = c("Parasitoids" = "black", 
                               "Caterpillars" = "black"))  +
  coord_cartesian(ylim = c(0, 1)) +
  labs(title = "Chao-Sorensen", x = "Guild", y = "Dissimilarity", fill = "Guild") +  # Keep only one legend for 'fill'
  theme_classic(base_size = 20) ;CS_FIG_1_simple

# Display the plot
CS_FIG_1_simple


# Ensure 'guild' is a factor with the desired order
ind_SOR$guild <- factor(ind_SOR$guild, 
                              levels = c("Parasitoids", "Caterpillars"))
# Create the plot
SOR_FIG_1_simple <- ggplot(ind_SOR_simple, aes(x = guild, y = hodnota, fill = guild)) +
  geom_violin(trim = FALSE) +  # Violin plot without trimming
  geom_boxplot(width = 0.1, outlier.shape = NA) +  # Boxplot with no outliers shown
  geom_jitter(position = position_jitter(0.2), aes(color = guild), show.legend = FALSE) +  # Jitter with color, no legend
   scale_fill_manual(values = c("Parasitoids" = "darkgreen", 
                               "Caterpillars" = "darkorange")) +
  scale_color_manual(values = c("Parasitoids" = "black", 
                               "Caterpillars" = "black"))  +
  coord_cartesian(ylim = c(0, 1)) +
  labs(title = "Sorensen", x = "Guild", y = "Dissimilarity", fill = "Guild") +  # Keep only one legend for 'fill'
  theme_classic(base_size = 20) ;SOR_FIG_1_simple

# Display the plot
SOR_FIG_1_simple

Fig_1_final_new_simple <-ggarrange(BC_FIG_1_simple, CS_FIG_1_simple, SOR_FIG_1_simple, common.legend = TRUE, legend = "bottom", nrow = 1)
Fig_1_final_new_simple
ggsave("output/fig/Fig_1_final_new_simple.tiff",
       Fig_1_final_new_simple,
       height = 14,
       width = 29,
       units = "cm")   # save the plot as .tiff

```

# Figure 1 - with distance
```{r}
figure_1_merged <- rbind(BC_par, BC_cat, BC_fig_subsampled, CS_par, CS_cat, CS_fig_subsampled,SOR_par, SOR_cat, SOR_fig_subsampled)



ind_BC <- figure_1_merged %>% 
  dplyr::filter(indexy == "Bray-Curtis")

ind_CS <- figure_1_merged %>% 
  dplyr::filter(indexy == "Chao-Sorensen")

ind_Sor <- figure_1_merged %>% 
  dplyr::filter(indexy == "Sorensen")





# Bray-Curtis
BC_FIG_1 <-ggplot(ind_BC, aes(x = distance, y = hodnota, 
                                color = guild, shape = guild, linetype = guild)) +
  geom_point(size = 3) +  # Adjust size as needed
  geom_smooth(method = "lm", se = FALSE, aes(group = guild), formula = y ~ x, fullrange = TRUE) +
  scale_color_manual(values = c("Parasitoids" = "darkgreen", 
                                "Caterpillars" = "darkorange", 
                                "Caterpillars-subsampled" = "#ffb681")) +
  scale_shape_manual(values = c("Parasitoids" = 17,  # Triangle
                                "Caterpillars" = 16,  # Full Circle
                                "Caterpillars-subsampled" = 1)) +  # Empty Circle
  scale_linetype_manual(values = c("Parasitoids" = "solid", 
                                   "Caterpillars" = "solid", 
                                   "Caterpillars-subsampled" = "dashed")) +
  coord_cartesian(ylim = c(0, 1)) +
  theme_minimal() +
  labs(title = "Bray-Curtis",
       x = "",
       y = "",
       color = "Guild",   # Change legend title for color
       shape = "Guild",   # Change legend title for shape
       linetype = "Guild")  +
  theme_classic(base_size = 20)  ;BC_FIG_1 

CS_FIG_1 <-ggplot(ind_CS, aes(x = distance, y = hodnota, 
                                color = guild, shape = guild, linetype = guild)) +
  geom_point(size = 3) +  # Adjust size as needed
  geom_smooth(method = "lm", se = FALSE, aes(group = guild), formula = y ~ x, fullrange = TRUE) +
  scale_color_manual(values = c("Parasitoids" = "darkgreen", 
                                "Caterpillars" = "darkorange", 
                                "Caterpillars-subsampled" = "#ffb681")) +
  scale_shape_manual(values = c("Parasitoids" = 17,  # Triangle
                                "Caterpillars" = 16,  # Full Circle
                                "Caterpillars-subsampled" = 1)) +  # Empty Circle
  scale_linetype_manual(values = c("Parasitoids" = "solid", 
                                   "Caterpillars" = "solid", 
                                   "Caterpillars-subsampled" = "dashed")) +
  coord_cartesian(ylim = c(0, 1)) +
  theme_minimal() +
  labs(title = "Chao-Sorensen",
       x = "",
       y = "",
       color = "Guild",   # Change legend title for color
       shape = "Guild",   # Change legend title for shape
       linetype = "Guild") +
  theme_classic(base_size = 20)  ;CS_FIG_1  


SOR_FIG_1 <-ggplot(ind_Sor, aes(x = distance, y = hodnota, 
                                  color = guild, shape = guild, linetype = guild)) +
  geom_point(size = 3) +  # Adjust size as needed
  geom_smooth(method = "lm", se = FALSE, aes(group = guild), formula = y ~ x, fullrange = TRUE) +
  scale_color_manual(values = c("Parasitoids" = "darkgreen", 
                                "Caterpillars" = "darkorange", 
                                "Caterpillars-subsampled" = "#ffb681")) +
  scale_shape_manual(values = c("Parasitoids" = 17,  # Triangle
                                "Caterpillars" = 16,  # Full Circle
                                "Caterpillars-subsampled" = 1)) +  # Empty Circle
  scale_linetype_manual(values = c("Parasitoids" = "solid", 
                                   "Caterpillars" = "solid", 
                                   "Caterpillars-subsampled" = "dashed")) +
  coord_cartesian(ylim = c(0, 1)) +
  theme_minimal() +
  labs(title = "Sorensen",
       x = "",
       y = "β diversity",
       color = "Guild",   # Change legend title for color
       shape = "Guild",   # Change legend title for shape
       linetype = "Guild") +  # Change legend title for linetype
  theme_classic(base_size = 20) ; SOR_FIG_1


Fig_1_final_new <-ggarrange(SOR_FIG_1 , CS_FIG_1 , BC_FIG_1, common.legend = TRUE, legend = "bottom", nrow = 1)
Fig_1_final_new
ggsave("output/fig/Fig_1_final_new.tiff",
       Fig_1_final_new,
       height = 14,
       width = 29,
       units = "cm")   # save the plot as .tiff





```

# Figure 1 No Ohu2

```{r}
##### No Ohu 2 in data


figure_1_merged_no_ohu <- figure_1_merged %>% 
  dplyr::filter(!(Locality_A == "Ohu2" | Locality_B == "Ohu2"))
ind_BC_no_Ohu <- figure_1_merged_no_ohu %>% 
  dplyr::filter(indexy == "Bray-Curtis")

ind_CS_no_Ohu <- figure_1_merged_no_ohu %>% 
  dplyr::filter(indexy == "Chao-Sorensen")

ind_Sor_no_Ohu <- figure_1_merged_no_ohu %>% 
  dplyr::filter(indexy == "Sorensen")


# Ensure 'guild' is a factor with the desired order
ind_BC_no_Ohu$guild <- factor(ind_BC_no_Ohu$guild, 
                              levels = c("Parasitoids", "Caterpillars", "Caterpillars-subsampled"))

# Create the plot
BC_FIG_1_no_OHU <- ggplot(ind_BC_no_Ohu, aes(x = guild, y = hodnota, fill = guild)) +
  geom_violin(trim = FALSE) +  # Violin plot without trimming
  geom_boxplot(width = 0.1, outlier.shape = NA) +  # Boxplot with no outliers shown
  geom_jitter(position = position_jitter(0.2), aes(color = guild), show.legend = FALSE) +  # Jitter with color, no legend
  scale_fill_manual(values = c("Parasitoids" = "darkgreen", 
                               "Caterpillars" = "darkorange", 
                               "Caterpillars-subsampled" = "#ffb681")) +
  scale_color_manual(values = c("Parasitoids" = "black", 
                                "Caterpillars" = "black", 
                                "Caterpillars-subsampled" = "black")) +
  coord_cartesian(ylim = c(0, 1)) +
  labs(title = "Bray-Curtis", x = "Guild", y = "Dissimilarity", fill = "Guild") +  # Keep only one legend for 'fill'
  theme_classic(base_size = 20)

# Display the plot
BC_FIG_1_no_OHU

```


# Rarity and common species of parasitoids
```{r}
common_par <- MASTER %>%
  filter(rarity == "0") %>%
  select (locality, PAR_sp)

rare_par <- MASTER %>%
  filter(rarity == "1") %>%
  select (locality, PAR_sp)

para_pivot2c <- as.matrix(table(common_par$locality, common_par$PAR_sp))  # dataframe ready for indices
para_pivot2c[is.na(para_pivot2c)] <- 0 # Replacing NA values with 0
para_pivot_P_Ac <- para_pivot2c
para_pivot_P_Ac [para_pivot_P_Ac > 0] <- 1 #converts from abundance to P/A - for Sorensen index only

#Bray-Curtis index for parasitoids
BC_par_resc <- vegdist(para_pivot2c, method="bray", binary=FALSE, diag=TRUE) %>% as.matrix()
BC_res_par_mantelc <- mantel(BC_par_resc, Distance , method="spear"); BC_res_par_mantel



####preparation for a figure - Bray-Curtis
Bray_C_parasitoidsc <- melt(BC_par_resc)
Bray_C_figure_parc <- Bray_C_parasitoidsc %>%
  add_column(guild = "Rare")
Bray_C_figure_parc <- Bray_C_figure_parc %>%
  dplyr::rename(Locality_A = X1, Locality_B = X2, hodnota=value)

par_fig_table_BCc <-merge(Bray_C_figure_parc, distance_plot, by=c("Locality_A", "Locality_B")) %>% 
  filter (hodnota > 0)



################ Tady

para_pivot2ra <- as.matrix(table(rare_par$locality, rare_par$PAR_sp))  # dataframe ready for indices
para_pivot2ra[is.na(para_pivot2ra)] <- 0 # Replacing NA values with 0
para_pivot_P_Ara <- para_pivot2ra
para_pivot_P_Ara [para_pivot_P_Ara > 0] <- 1 #converts from abundance to P/A - for Sorensen index only

#Bray-Curtis index for parasitoids
BC_par_resra <- vegdist(para_pivot2ra, method="bray", binary=FALSE, diag=TRUE) %>% as.matrix()
BC_res_par_mantelra <- mantel(BC_par_resra, Distance , method="spear"); BC_res_par_mantel



####preparation for a figure - Bray-Curtis
Bray_C_parasitoidsra <- melt(BC_par_resra)
Bray_C_figure_parra <- Bray_C_parasitoidsra %>%
  add_column(guild = "rare")
Bray_C_figure_parra <- Bray_C_figure_parra %>%
  dplyr::rename(Locality_A = X1, Locality_B = X2, hodnota=value)

par_fig_table_BCra <-merge(Bray_C_figure_parra, distance_plot, by=c("Locality_A", "Locality_B")) %>% 
  filter (hodnota > 0)

bray_common_rare <- rbind(par_fig_table_BCra,par_fig_table_BCc)



ggplot(bray_common_rare, aes(y = hodnota, 
                 color = guild, shape = guild, linetype = guild)) +
  geom_boxplot() +  # Adjust size as needed
  coord_cartesian(ylim = c(0, 1)) +
  theme_minimal() +
    theme_classic(base_size = 20)





```


# Tabulka celistvá
```{r Tabulka}
# Tabulka with rarity of parasitoids
tabulka_rarity <- rbind(mantel_result_Par_BC_common_plants, mantel_result_Par_BC_rare_common_plants, mantel_result_Par_BC_common_common_plants,
mantel_result_Par_CS_common_plants_all, mantel_result_Par_CS_rare_common_plants, mantel_result_Par_CS_common_common_plants,
mantel_result_Par_sor_common_common_plants_all,mantel_result_Par_sor_rare_common_plants,  mantel_result_Par_sor_common_common_plants) ;tabulka_rarity


# Tabulka without OHU2
Mantel_table_8 <- rbind(all_mantel_results_8, all_mantel_results_8_sub )


Mantel_table <- rbind(all_mantel_results, Mantel_table_8, tabulka_rarity )

# Round numeric columns to three decimal places
Mantel_table <- Mantel_table %>%
  dplyr::mutate(across(c(mean, sd, test_statistic, p.value), ~ round(., 3)))

# Format the table using gt
Mantel_gt <-Mantel_table %>%
  gt() %>%
  tab_header(
    title = "Mantel test results",
  ) %>%
  cols_label(
    index = "Index",
    Community = "Community",
    mean = "Mean",
    sd = "SD",
    statistic = "Test Statistic",
    p.value = "P-Value",
    Dataset = "Dataset"
  ) %>%
  tab_style(
    style = list(cell_text(align = "center")),
    locations = cells_body()
  )

gtsave(Mantel_gt, "Mantel_Test_Results.png")

library(openxlsx)

# Save the Mantel_table as an Excel file
write.xlsx(Mantel_table, "Mantel_Test_Results.xlsx")


```
