
```{r}
library(ggplot2)
library(ggpubr)
```


```{r}

```

Figure 1
```{r Figure 1}

indexy <-
  readr::read_delim(
    here::here(
      "DATA/index_all_fig.csv"
    ),
    delim = ";"
  ) %>%
  tibble::as_tibble()



index_CS <- indexy %>% 
  dplyr::filter(Index == "Chao-Sorensen")
index_BC <- indexy %>% 
  dplyr::filter(Index == "Bray-Curtis")
index_SOR <- indexy %>% 
  dplyr::filter(Index == "Sorensen")

### set up colours 
# Bray-Curtis
BC_FIG_1 <- ggplot(index_BC, aes(x = distance, y = hodnota, 
                 color = guild, shape = guild, linetype = guild)) +
  geom_point(size = 3) +  # Adjust size as needed
  geom_smooth(method = "lm", se = FALSE, aes(group = guild), formula = y ~ x, fullrange = TRUE) +
  scale_color_manual(values = c("Parasitoids" = "darkgreen", 
                                "Caterpillars" = "darkorange", 
                                "Caterpillars - subsampled" = "#ffb681")) +
  scale_shape_manual(values = c("Parasitoids" = 17,  # Triangle
                                "Caterpillars" = 16,  # Full Circle
                                "Caterpillars - subsampled" = 1)) +  # Empty Circle
  scale_linetype_manual(values = c("Parasitoids" = "solid", 
                                   "Caterpillars" = "solid", 
                                   "Caterpillars - subsampled" = "dashed")) +
  coord_cartesian(ylim = c(0, 1)) +
  labs(title = "Bray-Curtis",
       x = "",
       y = "",
       color = "Guild",   # Change legend title for color
       shape = "Guild",   # Change legend title for shape
       linetype = "Guild") +
  theme_classic(base_size = 16) +
  theme(text = element_text(family = "Arial"))  # Set font to Arial

BC_FIG_1


CS_FIG_1 <-ggplot(index_CS, aes(x = distance, y = hodnota, 
                 color = guild, shape = guild, linetype = guild)) +
  geom_point(size = 3) +  # Adjust size as needed
  geom_smooth(method = "lm", se = FALSE, aes(group = guild), formula = y ~ x, fullrange = TRUE) +
  scale_color_manual(values = c("Parasitoids" = "darkgreen", 
                                "Caterpillars" = "darkorange", 
                                "Caterpillars - subsampled" = "#ffb681")) +
  scale_shape_manual(values = c("Parasitoids" = 17,  # Triangle
                                "Caterpillars" = 16,  # Full Circle
                                "Caterpillars - subsampled" = 1)) +  # Empty Circle
  scale_linetype_manual(values = c("Parasitoids" = "solid", 
                                   "Caterpillars" = "solid", 
                                   "Caterpillars - subsampled" = "dashed")) +
  coord_cartesian(ylim = c(0, 1)) +
  theme_minimal() +
  labs(title = "Chao-Sorensen",
         x = "km",
       y = "",
       color = "Guild",   # Change legend title for color
       shape = "Guild",   # Change legend title for shape
       linetype = "Guild") +
  theme_classic(base_size = 16)+
  theme(text = element_text(family = "Arial"))   ;CS_FIG_1  


SOR_FIG_1 <-ggplot(index_SOR, aes(x = distance, y = hodnota, 
                 color = guild, shape = guild, linetype = guild)) +
  geom_point(size = 3) +  # Adjust size as needed
  geom_smooth(method = "lm", se = FALSE, aes(group = guild), formula = y ~ x, fullrange = TRUE) +
  scale_color_manual(values = c("Parasitoids" = "darkgreen", 
                                "Caterpillars" = "darkorange", 
                                "Caterpillars - subsampled" = "#ffb681")) +
  scale_shape_manual(values = c("Parasitoids" = 17,  # Triangle
                                "Caterpillars" = 16,  # Full Circle
                                "Caterpillars - subsampled" = 1)) +  # Empty Circle
  scale_linetype_manual(values = c("Parasitoids" = "solid", 
                                   "Caterpillars" = "solid", 
                                   "Caterpillars - subsampled" = "dashed")) +
  coord_cartesian(ylim = c(0, 1)) +
  theme_minimal() +
  labs(title = "Sorensen",
       x = "",
       y = "β diversity",
       color = "Guild",   # Change legend title for color
       shape = "Guild",   # Change legend title for shape
       linetype = "Guild") +  # Change legend title for linetype
  theme_classic(base_size = 16) +
  theme(text = element_text(family = "Arial"))  ; SOR_FIG_1


Fig_1_final <-ggarrange(SOR_FIG_1 , CS_FIG_1 , BC_FIG_1, common.legend = TRUE, legend = "bottom", nrow = 1)

Fig_1_final
ggsave("output/fig/Fig_1.tiff",
Fig_1_final,
 width = 8.7,      # Single column width in inches
       height = 6,       # Adjust as needed
       dpi = 600)   # save the plot as .tiff

```


```{r Figure 2}
# WN
# Ensure "CAT-PLANT Subsampled" is added as a level
levels(graf_WN$dataset_type) <- c(levels(graf_WN$dataset_type), "CAT-PLANT Subsampled")

# Replace "Subsampled" with "Petr"
graf_WN$dataset_type[graf_WN$dataset_type == "Subsampled"] <- "CAT-PLANT Subsampled"

#compare_means(value ~ dataset_type,  data = graf_WN)



Fig_WN <- ggplot(graf_WN, aes(x = dataset_type, y = value, color = dataset_type, shape = dataset_type, alpha = dataset_type)) +
  geom_boxplot(colour = "black", width=0.5) +
  geom_jitter(size = 2, position=position_jitter(0.2)) +
  labs(
    title = "WN-General dissimilarity",
    x = "",
    y = "Dissimilarity",
    color = "",      # Change legend title for color
    shape = "",      # Change legend title for shape
    alpha = ""       # Change legend title for alpha
  )  + 
   scale_alpha_manual(
    values = c("PAR-CAT" = 0.7, "CAT-PLANT" = 0.7, "CAT-PLANT Subsampled" = 0.5),
    labels = c("PAR-CAT" = "Parasitoid-Caterpillar", 
               "CAT-PLANT" = "Caterpillar-Plant", 
               "CAT-PLANT Subsampled" = "Caterpillar-Plant Subsampled")
  ) +
  scale_color_manual(
    values = c("PAR-CAT" = "#1b9e77", "CAT-PLANT" = "#d95f02", "CAT-PLANT Subsampled" = "#ffb681"),
    labels = c("PAR-CAT" = "Parasitoid-Caterpillar", 
               "CAT-PLANT" = "Caterpillar-Plant", 
               "CAT-PLANT Subsampled" = "Caterpillar-Plant Subsampled")
  ) +
  scale_shape_manual(
    values = c("PAR-CAT" = 17, "CAT-PLANT" = 16, "CAT-PLANT Subsampled" = 16),
    labels = c("PAR-CAT" = "Parasitoid-Caterpillar", 
               "CAT-PLANT" = "Caterpillar-Plant", 
               "CAT-PLANT Subsampled" = "Caterpillar-Plant Subsampled")
  )+
  coord_cartesian(ylim = c(0, 1.15)) +
  scale_y_continuous(breaks = seq(0, 1.15, by = 0.25)) + 
  theme_classic(base_size = 20) +
  theme (axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
   geom_signif(
    comparisons = list(c("PAR-CAT", "CAT-PLANT"), c ( "PAR-CAT", "CAT-PLANT Subsampled"), c("CAT-PLANT", "CAT-PLANT Subsampled")),
    map_signif_level = TRUE,
    textsize = 6,
    margin_top = 0.1,
    step_increase = 0.15,
    tip_length = 0.01,
    color = "black")
Fig_WN# Add pairwise comparisons p-value  ; Fig_WN


# ST
# Ensure "CAT-PLANT Subsampled" is added as a level
levels(graf_ST$dataset_type) <- c(levels(graf_ST$dataset_type), "CAT-PLANT Subsampled")

# Replace "Subsampled" with "Petr"
graf_ST$dataset_type[graf_ST$dataset_type == "Subsampled"] <- "CAT-PLANT Subsampled"

#compare_means(value ~ dataset_type,  data = graf_ST)



Fig_ST <- ggplot(graf_ST, aes(x = dataset_type, y = value, color = dataset_type, shape = dataset_type, alpha = dataset_type)) +
  geom_boxplot(colour = "black", width=0.5) +
  geom_jitter(size = 2, position=position_jitter(0.2)) +
  labs(
    title = "ST-Species Turnover",
    x = "",
    y = "",
    color = "",      # Change legend title for color
    shape = "",      # Change legend title for shape
    alpha = ""       # Change legend title for alpha
  )  + 
  scale_alpha_manual(
    values = c("PAR-CAT" = 0.7, "CAT-PLANT" = 0.7, "CAT-PLANT Subsampled" = 0.5),
    labels = c("PAR-CAT" = "Parasitoid-Caterpillar", 
               "CAT-PLANT" = "Caterpillar-Plant", 
               "CAT-PLANT Subsampled" = "Caterpillar-Plant Subsampled")
  ) +
  scale_color_manual(
    values = c("PAR-CAT" = "#1b9e77", "CAT-PLANT" = "#d95f02", "CAT-PLANT Subsampled" = "#ffb681"),
    labels = c("PAR-CAT" = "Parasitoid-Caterpillar", 
               "CAT-PLANT" = "Caterpillar-Plant", 
               "CAT-PLANT Subsampled" = "Caterpillar-Plant Subsampled")
  ) +
  scale_shape_manual(
    values = c("PAR-CAT" = 17, "CAT-PLANT" = 16, "CAT-PLANT Subsampled" = 16),
    labels = c("PAR-CAT" = "Parasitoid-Caterpillar", 
               "CAT-PLANT" = "Caterpillar-Plant", 
               "CAT-PLANT Subsampled" = "Caterpillar-Plant Subsampled")
  ) +
  coord_cartesian(ylim = c(0, 1.15)) +
  scale_y_continuous(breaks = seq(0, 1.15, by = 0.25)) + 
  theme_classic(base_size = 20) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  geom_signif(
    comparisons = list(c("PAR-CAT", "CAT-PLANT"), c("PAR-CAT", "CAT-PLANT Subsampled"), c("CAT-PLANT", "CAT-PLANT Subsampled")),
    map_signif_level = TRUE,
    textsize = 6,
    margin_top = 0.1,
    step_increase = 0.15,
    tip_length = 0.01,
    color = "black"
  )

Fig_ST
# Add pairwise comparisons p-value  ; Fig_ST


# OS
# Ensure "CAT-PLANT Subsampled" is added as a level
levels(graf_OS$dataset_type) <- c(levels(graf_OS$dataset_type), "CAT-PLANT Subsampled")

# Replace "Subsampled" with "Petr"
graf_OS$dataset_type[graf_OS$dataset_type == "Subsampled"] <- "CAT-PLANT Subsampled"

#compare_means(value ~ dataset_type,  data = graf_OS)



Fig_OS <- ggplot(graf_OS, aes(x = dataset_type, y = value, color = dataset_type, shape = dataset_type, alpha = dataset_type)) +
  geom_boxplot(colour = "black", width=0.5) +
  geom_jitter(size = 2, position=position_jitter(0.2)) +
  labs(
    title = "OS-Rewiring",
    x = "",
    y = "",
    color = "",      # Change legend title for color
    shape = "",      # Change legend title for shape
    alpha = ""       # Change legend title for alpha
  )  + 
  scale_alpha_manual(
    values = c("PAR-CAT" = 0.7, "CAT-PLANT" = 0.7, "CAT-PLANT Subsampled" = 0.5),
    labels = c("PAR-CAT" = "Parasitoid-Caterpillar", 
               "CAT-PLANT" = "Caterpillar-Plant", 
               "CAT-PLANT Subsampled" = "Caterpillar-Plant Subsampled")
  ) +
  scale_color_manual(
    values = c("PAR-CAT" = "#1b9e77", "CAT-PLANT" = "#d95f02", "CAT-PLANT Subsampled" = "#ffb681"),
    labels = c("PAR-CAT" = "Parasitoid-Caterpillar", 
               "CAT-PLANT" = "Caterpillar-Plant", 
               "CAT-PLANT Subsampled" = "Caterpillar-Plant Subsampled")
  ) +
  scale_shape_manual(
    values = c("PAR-CAT" = 17, "CAT-PLANT" = 16, "CAT-PLANT Subsampled" = 16),
    labels = c("PAR-CAT" = "Parasitoid-Caterpillar", 
               "CAT-PLANT" = "Caterpillar-Plant", 
               "CAT-PLANT Subsampled" = "Caterpillar-Plant Subsampled")
  ) +
  coord_cartesian(ylim = c(0, 1.15)) +
  scale_y_continuous(breaks = seq(0, 1.15, by = 0.25)) + 
  theme_classic(base_size = 20) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  geom_signif(
    comparisons = list(c("PAR-CAT", "CAT-PLANT"), c("PAR-CAT", "CAT-PLANT Subsampled"), c("CAT-PLANT", "CAT-PLANT Subsampled")),
    map_signif_level = TRUE,
    textsize = 6,
    margin_top = 0.1,
    step_increase = 0.25,
    tip_length = 0.01,
    color = "black"
  )

# Add pairwise comparisons p-value  ; Fig_OS


Fig_2_final <-ggarrange(Fig_WN, Fig_OS, Fig_ST, common.legend = TRUE, legend = "bottom", nrow = 1)

Fig_2_final
ggsave("output/fig/Fig_2_final.tiff",
Fig_2_final,
height = 17,
width = 28,
units = "cm")   # save the plot as .tiff




```

Figure S2
```{r FigS2}
# Load necessary libraries
library(ggplot2)
library(dplyr)
library(gridExtra)  # For combining plots

# Combine dissimilarity data
dissimilarity_data <- data.frame(
  Guild = c(
    rep("Parasitoids", length(sorensen_values_PAR)),
    rep("Caterpillars", length(sorensen_values_CAT)),
    rep("Parasitoids", length(chao_sorensen_values_PAR)),
    rep("Caterpillars", length(chao_sorensen_values_CAT)),
    rep("Parasitoids", length(bray_curtis_values_PAR)),
    rep("Caterpillars", length(bray_curtis_values_CAT))
  ),
  Dissimilarity = c(
    sorensen_values_PAR,
    sorensen_values_CAT,
    chao_sorensen_values_PAR,
    chao_sorensen_values_CAT,
    bray_curtis_values_PAR,
    bray_curtis_values_CAT
  ),
  Index = c(
    rep("Sorensen", length(sorensen_values_PAR) + length(sorensen_values_CAT)),
    rep("Chao-Sorensen", length(chao_sorensen_values_PAR) + length(chao_sorensen_values_CAT)),
    rep("Bray-Curtis", length(bray_curtis_values_PAR) + length(bray_curtis_values_CAT))
  )
)

# Create the first plot (Dissimilarity of Parasitoids and Caterpillars)
plot1 <- ggplot(dissimilarity_data, aes(x = Index, y = Dissimilarity, fill = Guild)) +
  geom_boxplot() +
  labs(
    title = "Dissimilarity of parasitoids and caterpillars\nat Ohu locality",
    x = "Dissimilarity index",
    y = "Dissimilarity"
  ) +
  coord_cartesian(ylim = c(0, 1)) +
  scale_fill_manual(name = "Community",
                    values = c("Parasitoids" = "darkgreen", "Caterpillars" = "darkorange")) +
  theme_classic(base_size = 16) +
  theme(
    legend.position = "bottom"
  )

# Combine the beta values into one vector with an associated category and source
combined_data <- data.frame(
  beta_value = c(betaS_values_PC, betaOS_values_PC, betaWN_values_PC,
                 betaS_values_CPL, betaOS_values_CPL, betaWN_values_CPL),
  category = c(rep("S", length(betaS_values_PC)),
               rep("OS", length(betaOS_values_PC)),
               rep("WN", length(betaWN_values_PC)),
               rep("S", length(betaS_values_CPL)),
               rep("OS", length(betaOS_values_CPL)),
               rep("WN", length(betaWN_values_CPL))),
  source = c(rep("PC", length(betaS_values_PC)),
             rep("PC", length(betaOS_values_PC)),
             rep("PC", length(betaWN_values_PC)),
             rep("CPL", length(betaS_values_CPL)),
             rep("CPL", length(betaOS_values_CPL)),
             rep("CPL", length(betaWN_values_CPL)))
)

# Ensure the 'source' column is a factor with the desired order
combined_data$source <- factor(combined_data$source, levels = c("PC", "CPL"))

# Create the second plot (Food-Web Interaction Dissimilarity)
plot2 <- ggplot(combined_data, aes(x = category, y = beta_value, fill = source)) +
  geom_boxplot() +
  labs(title = "Food-Web interaction dissimilarity\nat Ohu locality",
       x = "Components", y = "") +
  coord_cartesian(ylim = c(0, 1)) +
  theme_minimal() +
  scale_fill_manual(name = "Food-Web", 
                    values = c("PC" = "#1b9e77", "CPL" = "#d95f02"),
                    labels = c("PC" = "Parasitoid-Caterpillar", 
                               "CPL" = "Caterpillar-Plant")) +
  theme_classic(base_size = 16) +
  theme(
    legend.position = "bottom"
  )

# Combine both plots into one grid
grid.arrange(plot1, plot2, ncol = 2)



library(cowplot)

# Add labels to the plots
plot1_labeled <- ggdraw() +
  draw_plot(plot1) +
  draw_label("A", x = 0.03, y = 0.97, hjust = 0, vjust = 1, size = 15)

plot2_labeled <- ggdraw() +
  draw_plot(plot2) +
  draw_label("B", x = 0.03, y = 0.97, hjust = 0, vjust = 1, size = 15)

# Combine both plots into one grid
Fig_S2_final <- plot_grid(plot1_labeled, plot2_labeled, ncol = 2, align = "v")
print(Fig_S2_final)


Fig_S2_final
ggsave("output/fig/Fig_S2_final.tiff",
       Fig_S2_final,
       width = 11.7,      # Single column width in inches
       height = 6,       # Adjust as needed
       dpi = 300)   # save the plot as .tiff

```

